// Code generated by goctl. DO NOT EDIT!
// Source: add.proto

package server

import (
	"context"

	"bookstore/rpc/add/add"
	"bookstore/rpc/add/internal/logic"
	"bookstore/rpc/add/internal/svc"
)

type AddServer struct {
	svcCtx *svc.ServiceContext
}

func NewAddServer(svcCtx *svc.ServiceContext) *AddServer {
	return &AddServer{
		svcCtx: svcCtx,
	}
}

func (s *AddServer) Add(ctx context.Context, in *add.Request) (*add.Response, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}
