// Code generated by goctl. DO NOT EDIT!
// Source: add.proto

package adder

import (
	"context"

	"bookstore/rpc/add/add"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	Request  = add.Request
	Response = add.Response

	Adder interface {
		Add(ctx context.Context, in *Request) (*Response, error)
	}

	defaultAdder struct {
		cli zrpc.Client
	}
)

func NewAdder(cli zrpc.Client) Adder {
	return &defaultAdder{
		cli: cli,
	}
}

func (m *defaultAdder) Add(ctx context.Context, in *Request) (*Response, error) {
	client := add.NewAdderClient(m.cli.Conn())
	return client.Add(ctx, in)
}
